swagger: "2.0"
info:
  title: Wargame Service
  description: HTTP service for the SSM Wargame
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /admin/challenges:
    get:
      tags:
      - admin
      summary: ListChallenges admin
      operationId: admin#ListChallenges
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AdminSsmChallengeResponseCollection'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
    post:
      tags:
      - admin
      summary: CreateChallenge admin
      operationId: admin#CreateChallenge
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
      - name: CreateChallengeRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AdminCreateChallengeRequestBody'
          required:
          - id
          - title
          - description
          - score
          - published
          - slug
          - solves
      responses:
        "201":
          description: Created response.
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /auth/discord/exchange:
    post:
      tags:
      - auth
      summary: ExchangeDiscord auth
      operationId: auth#ExchangeDiscord
      parameters:
      - name: ExchangeDiscordRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AuthExchangeDiscordRequestBody'
          required:
          - code
          - state
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuthExchangeDiscordResponseBody'
            required:
            - jwt
      schemes:
      - http
  /auth/discord/url:
    get:
      tags:
      - auth
      summary: GenerateDiscordAuthURL auth
      operationId: auth#GenerateDiscordAuthURL
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuthGenerateDiscordAuthURLResponseBody'
            required:
            - url
      schemes:
      - http
  /challenges:
    get:
      tags:
      - challenge
      summary: ListChallenges challenge
      operationId: challenge#ListChallenges
      parameters:
      - name: Authorization
        in: header
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChallengeSsmChallengeResponseCollection'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /challenges/{challengeID}/attempt:
    post:
      tags:
      - challenge
      summary: SubmitFlag challenge
      operationId: challenge#SubmitFlag
      parameters:
      - name: challengeID
        in: path
        required: true
        type: string
        format: uuid
      - name: Authorization
        in: header
        required: true
        type: string
      - name: SubmitFlagRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ChallengeSubmitFlagRequestBody'
          required:
          - flag
      responses:
        "200":
          description: OK response.
        "400":
          description: If the challenge is already solved
          schema:
            $ref: '#/definitions/ChallengeSubmitFlagIncorrectFlagResponseBody'
        "409":
          description: If the challenge is already solved
          schema:
            $ref: '#/definitions/ChallengeSubmitFlagAlreadySolvedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /monthly_challenges:
    get:
      tags:
      - challenge
      summary: ListMonthlyChallenges challenge
      operationId: challenge#ListMonthlyChallenges
      parameters:
      - name: Authorization
        in: header
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ChallengeSsmMonthlyChallengeResponseCollection'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
definitions:
  AdminCreateChallengeRequestBody:
    title: AdminCreateChallengeRequestBody
    type: object
    properties:
      description:
        type: string
        description: A short text describing the challenge
        example: A heap overflow challenge
      score:
        type: integer
        description: The number of points given to the solver
        example: 50
        format: int32
      slug:
        type: string
        description: A unique string that can be used in URLs
        example: pwnme
      title:
        type: string
        description: Title displayed to user
        example: pwnme
    example:
      description: A heap overflow challenge
      score: 50
      slug: pwnme
      title: pwnme
    required:
    - id
    - title
    - description
    - score
    - published
    - slug
    - solves
  AdminSsmChallengeResponseCollection:
    title: 'Mediatype identifier: application/vnd.ssm.challenge; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/SsmChallengeResponse'
    description: ListChallengesResponseBody is the result type for an array of SsmChallengeResponse
      (default view)
    example:
    - description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
    - description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
    - description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
  AuthExchangeDiscordRequestBody:
    title: AuthExchangeDiscordRequestBody
    type: object
    properties:
      code:
        type: string
        example: 123abc
      state:
        type: string
        example: 15773059ghq9183habn
    example:
      code: 123abc
      state: 15773059ghq9183habn
    required:
    - code
    - state
  AuthExchangeDiscordResponseBody:
    title: AuthExchangeDiscordResponseBody
    type: object
    properties:
      jwt:
        type: string
        description: A token to authenticate with the SSM API
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    example:
      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    required:
    - jwt
  AuthGenerateDiscordAuthURLResponseBody:
    title: AuthGenerateDiscordAuthURLResponseBody
    type: object
    properties:
      url:
        type: string
        example: https://discord.com/api/oauth2/authorize?response_type=code&client_id=157730590492196864&scope=identify%20guilds.join&state=15773059ghq9183habn&redirect_uri=https%3A%2F%2Fnicememe.website&prompt=consent
    example:
      url: https://discord.com/api/oauth2/authorize?response_type=code&client_id=157730590492196864&scope=identify%20guilds.join&state=15773059ghq9183habn&redirect_uri=https%3A%2F%2Fnicememe.website&prompt=consent
    required:
    - url
  ChallengeFilesResponse:
    title: ChallengeFilesResponse
    type: object
    example: {}
  ChallengeServiceResponse:
    title: ChallengeServiceResponse
    type: object
    example: {}
  ChallengeSsmChallengeResponseCollection:
    title: 'Mediatype identifier: application/vnd.ssm.challenge; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/SsmChallengeResponse'
    description: ListChallengesResponseBody is the result type for an array of SsmChallengeResponse
      (default view)
    example:
    - description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
    - description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
    - description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
  ChallengeSsmMonthlyChallengeResponseCollection:
    title: 'Mediatype identifier: application/vnd.ssm.monthly.challenge; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/SsmMonthlyChallengeResponse'
    description: ListMonthlyChallengesResponseBody is the result type for an array
      of SsmMonthlyChallengeResponse (default view)
    example:
    - display_month: Januari/Februari
      end_date: "2006-02-01"
      start_date: "2006-02-01"
    - display_month: Januari/Februari
      end_date: "2006-02-01"
      start_date: "2006-02-01"
    - display_month: Januari/Februari
      end_date: "2006-02-01"
      start_date: "2006-02-01"
    - display_month: Januari/Februari
      end_date: "2006-02-01"
      start_date: "2006-02-01"
  ChallengeSubmitFlagAlreadySolvedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: SubmitFlag_already_solved_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ChallengeSubmitFlagIncorrectFlagResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: SubmitFlag_incorrect_flag_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ChallengeSubmitFlagRequestBody:
    title: ChallengeSubmitFlagRequestBody
    type: object
    properties:
      flag:
        type: string
        example: SSM{flag}
        maxLength: 200
    example:
      flag: SSM{flag}
    required:
    - flag
  SsmChallengeResponse:
    title: 'Mediatype identifier: application/vnd.ssm.challenge; view=default'
    type: object
    properties:
      description:
        type: string
        description: A short text describing the challenge
        example: A heap overflow challenge
      files:
        type: array
        items:
          $ref: '#/definitions/ChallengeFilesResponse'
        example:
        - {}
        - {}
      id:
        type: string
        example: e721a338-44de-4de8-a562-43d2db5f4115
      published:
        type: boolean
        example: true
      score:
        type: integer
        description: The number of points given to the solver
        example: 50
        format: int32
      services:
        type: array
        items:
          $ref: '#/definitions/ChallengeServiceResponse'
        example:
        - {}
        - {}
        - {}
        - {}
      slug:
        type: string
        description: A unique string that can be used in URLs
        example: pwnme
      solves:
        type: integer
        description: The numer of people who solved the challenge
        example: 3
        format: int64
      title:
        type: string
        description: Title displayed to user
        example: pwnme
    description: A Wargame challenge (default view)
    example:
      description: A heap overflow challenge
      files:
      - {}
      - {}
      id: e721a338-44de-4de8-a562-43d2db5f4115
      published: true
      score: 50
      services:
      - {}
      - {}
      - {}
      slug: pwnme
      solves: 3
      title: pwnme
    required:
    - id
    - title
    - description
    - score
    - published
    - slug
    - solves
  SsmMonthlyChallengeResponse:
    title: 'Mediatype identifier: application/vnd.ssm.monthly.challenge; view=default'
    type: object
    properties:
      display_month:
        type: string
        description: The month(s) that the challenge is assigned for
        example: Januari/Februari
      end_date:
        type: string
        description: Ending date of the monthly challenge
        example: "2006-02-01"
      start_date:
        type: string
        description: Starting date of the monthly challenge
        example: "2006-02-01"
    description: A monthly challenge (default view)
    example:
      display_month: Januari/Februari
      end_date: "2006-02-01"
      start_date: "2006-02-01"
    required:
    - start_date
    - end_date
    - display_month
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    name: Authorization
    in: header
